#!/bin/bash
# Script to copy experimental section PDFs to refs-experimental directory
# Run this script from the terminal to complete the PDF copying process

ZOTERO_STORAGE="/Users/yyangg00/Library/Mobile Documents/iCloud~md~obsidian/Documents/Vault/zotero_storage"
DEST_DIR="$ZOTERO_STORAGE/refs-experimental"

echo "Copying PDFs for 'Integration with Experimental Techniques' section..."
echo "Source: Lines 388-453 in Final Draft.tex"
echo "Destination: $DEST_DIR"
echo ""

# Create destination directory if it doesn't exist
mkdir -p "$DEST_DIR"

# Copy identified PDF files
cp "$ZOTERO_STORAGE/KYH4KAXI/Bailly et al. - 2020 - Predicting Antibody Developability Profiles Through Early Stage Discovery Screening.pdf" "$DEST_DIR/"
cp "$ZOTERO_STORAGE/ZSYVRKAQ/Canepa et al. - 2020 - Characterizing osmolyte chemical class hierarchies and functional group requirements for thermal sta.pdf" "$DEST_DIR/"
cp "$ZOTERO_STORAGE/QVA5UJQ5/Lenard et al. - 2022 - Solvent paramagnetic relaxation enhancement as a versatile method for studying structure and dynamic.pdf" "$DEST_DIR/"
cp "$ZOTERO_STORAGE/5DNWXYAU/Okuno et al. - 2021 - Atomic view of cosolute-induced protein denaturation probed by NMR solvent paramagnetic relaxation e.pdf" "$DEST_DIR/"
cp "$ZOTERO_STORAGE/GSP3M9UF/Okuno et al. - 2020 - Quantitative Interpretation of Solvent Paramagnetic Relaxation for Probing Protein–Cosolute Interact.pdf" "$DEST_DIR/"
cp "$ZOTERO_STORAGE/GU7PCSXH/Trevitt et al. - 2024 - Interactions between the protein barnase and co-solutes studied by NMR.pdf" "$DEST_DIR/"
cp "$ZOTERO_STORAGE/AUCGWYQI/Penk et al. - 2024 - Detecting Protein-Ligand Interactions with Nitroxide Based Paramagnetic Cosolutes.pdf" "$DEST_DIR/"
cp "$ZOTERO_STORAGE/LHYUT8CS/Tang et al. - 2023 - Crystal structures and molecular dynamics simulations of a humanised antibody fragment at acidic to.pdf" "$DEST_DIR/"
cp "$ZOTERO_STORAGE/3YTFV843/Yip et al. - 2020 - Atomic-resolution protein structure determination by cryo-EM.pdf" "$DEST_DIR/"
cp "$ZOTERO_STORAGE/DEHPTT23/Nakane et al. - 2020 - Single-particle cryo-EM at atomic resolution.pdf" "$DEST_DIR/"
cp "$ZOTERO_STORAGE/4QPVZUVF/Lyumkis - 2019 - Challenges and opportunities in cryo-EM single-particle analysis.pdf" "$DEST_DIR/"
cp "$ZOTERO_STORAGE/H68AAYN2/Yan et al. - 2018 - Architecture of the CBF3–centromere complex of the budding yeast kinetochore.pdf" "$DEST_DIR/"
cp "$ZOTERO_STORAGE/6QCSYSPY/Castellanos et al. - 2017 - Investigating Structure and Dynamics of Proteins in Amorphous Phases Using Neutron Scattering.pdf" "$DEST_DIR/"
cp "$ZOTERO_STORAGE/XW9IWLFP/Clark et al. - 2013 - Small-Angle Neutron Scattering Study of a Monoclonal Antibody Using Free-Energy Constraints.pdf" "$DEST_DIR/"
cp "$ZOTERO_STORAGE/23BZ38BK/Mohammadiarani et al. - 2018 - Interpreting Hydrogen-Deuterium Exchange Events in Proteins Using Atomistic Simulations Case Studie.pdf" "$DEST_DIR/"
cp "$ZOTERO_STORAGE/LVFD3KXN/Stofella et al. - 2025 - Recalibrating Protection Factors Using Millisecond HydrogenDeuterium Exchange Mass Spectrometry.pdf" "$DEST_DIR/"
cp "$ZOTERO_STORAGE/MI48WS66/Kihn et al. - 2024 - Integration of Hydrogen–Deuterium Exchange Mass Spectrometry with Molecular Dynamics Simulations and.pdf" "$DEST_DIR/"
cp "$ZOTERO_STORAGE/3NZGPNLQ/Wood et al. - 2020 - HDX and In Silico Docking Reveal that Excipients Stabilize G-CSF via a Combination of Preferential E.pdf" "$DEST_DIR/"
cp "$ZOTERO_STORAGE/M9QTGXR5/Berisha et al. - 2019 - Deep learning for FTIR histology leveraging spatial and spectral features with convolutional neural.pdf" "$DEST_DIR/"
cp "$ZOTERO_STORAGE/U9FXZSAP/Guo et al. - 2025 - Artificial Intelligence in Spectroscopy Advancing Chemistry from Prediction to Generation and Beyon.pdf" "$DEST_DIR/"
cp "$ZOTERO_STORAGE/HJS3MBFY/Venanzi et al. - 2020 - A spectroscopic and molecular dynamics study on the aggregation process of a long-acting lipidated t.pdf" "$DEST_DIR/"
cp "$ZOTERO_STORAGE/2ENX3WDY/Mosca et al. - 2023 - Biophysical Determinants for the Viscosity of Concentrated Monoclonal Antibody Solutions.pdf" "$DEST_DIR/"
cp "$ZOTERO_STORAGE/FDX7Z2KD/Gulotta et al. - 2024 - Combining Scattering Experiments and Colloid Theory to Characterize Charge Effects in Concentrated A.pdf" "$DEST_DIR/"
cp "$ZOTERO_STORAGE/ANQZRZVB/Jo et al. - 2020 - Computational Characterization of Antibody–Excipient Interactions for Rational Excipient Selection U.pdf" "$DEST_DIR/"
cp "$ZOTERO_STORAGE/CS2ALPT9/Chowdhury et al. - 2020 - Coarse-Grained Molecular Dynamics Simulations for Understanding the Impact of Short-Range Anisotropi.pdf" "$DEST_DIR/"
cp "$ZOTERO_STORAGE/DWKWUAKM/Zidar et al. - 2020 - Control of viscosity in biopharmaceutical protein formulations.pdf" "$DEST_DIR/"
cp "$ZOTERO_STORAGE/FV5HAZH3/Fukuda et al. - 2014 - Thermodynamic and Fluorescence Analyses to Determine Mechanisms of IgG1 Stabilization and Destabiliz.pdf" "$DEST_DIR/"
cp "$ZOTERO_STORAGE/9L9KE42R/Piana et al. - 2020 - Development of a Force Field for the Simulation of Single-Chain Proteins and Protein–Protein Complex.pdf" "$DEST_DIR/"
cp "$ZOTERO_STORAGE/PQGY855U/Cloutier et al. - 2020 - Molecular computations of preferential interactions of proline, arginine.HCl, and NaCl with IgG1 ant.pdf" "$DEST_DIR/"
cp "$ZOTERO_STORAGE/3MFL6SIP/Das et al. - 2007 - Inhibition of Protein Aggregation Supramolecular Assemblies of Arginine Hold the Key.pdf" "$DEST_DIR/"
cp "$ZOTERO_STORAGE/AT2QRMH3/Ghosh et al. - 2009 - Effect of Arginine on Protein Aggregation Studied by Fluorescence Correlation Spectroscopy and Other.pdf" "$DEST_DIR/"
cp "$ZOTERO_STORAGE/WH87KBTT/Ishibashi et al. - 2005 - Is arginine a protein-denaturant.pdf" "$DEST_DIR/"
cp "$ZOTERO_STORAGE/HICS6L47/Scherer - 2015 - Role of Cosolute–Protein Interactions in the Dissociation of Monoclonal Antibody Clusters.pdf" "$DEST_DIR/"
cp "$ZOTERO_STORAGE/9IW6GIZR/Shukla and Trout - 2010 - Interaction of Arginine with Proteins and the Mechanism by Which It Inhibits Aggregation.pdf" "$DEST_DIR/"
cp "$ZOTERO_STORAGE/2ESDY4YU/Ng and Konermann - 2024 - Mechanism of Protein Aggregation Inhibition by Arginine Blockage of Anionic Side Chains Favors Unpr.pdf" "$DEST_DIR/"
cp "$ZOTERO_STORAGE/TBLHNSNF/sharma2024ontherole.pdf" "$DEST_DIR/"
cp "$ZOTERO_STORAGE/MEQC26XF/Schneider et al. - 2011 - Arginine and the Hofmeister Series The Role of Ion–Ion Interactions in Protein Aggregation Suppress.pdf" "$DEST_DIR/"
cp "$ZOTERO_STORAGE/Q4ANDRKP/Zhang et al. - 2016 - Influence of Arginine Salts on the Thermal Stability and Aggregation Kinetics of Monoclonal Antibody.pdf" "$DEST_DIR/"
cp "$ZOTERO_STORAGE/A2A6SV2V/Tosstorff et al. - 2020 - Study of the interaction between a novel, protein-stabilizing dipeptide and Interferon-alpha-2a by c.pdf" "$DEST_DIR/"
cp "$ZOTERO_STORAGE/4I9FSL6D/Orr et al. - 2025 - Mapping the distribution and affinities of ligand interaction sites on human serum albumin.pdf" "$DEST_DIR/"
cp "$ZOTERO_STORAGE/K87L99BA/Obi and Deredge - 2021 - A Combined HDX-MS and MD Simulation Approach to Identify Potential Druggable Regions in the NS5 Prot.pdf" "$DEST_DIR/"
cp "$ZOTERO_STORAGE/6CCRQ8HI/Saporiti et al. - 2021 - IgG1 conformational behavior elucidation of the N-glycosylation role via molecular dynamics.pdf" "$DEST_DIR/"

echo "PDF copying completed!"
echo "Total files copied: $(ls -1 "$DEST_DIR"/*.pdf 2>/dev/null | wc -l)"
echo "Files are now available in: $DEST_DIR"